from pathlib import Path
import json,html
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'site'
def h(s):return html.escape(str(s),quote=True)
projects=[]
def project(slug,name,category,sector,desc,problem,solution,image='',url='',features=(),gallery=(),color='#5c73ff',label='Projeto de portfólio'):
 projects.append(dict(slug=slug,name=name,category=category,sector=sector,desc=desc,problem=problem,solution=solution,image=image,url=url,features=features,gallery=gallery,color=color,label=label))
sitebase='https://{}.esconsultoria01.chatgpt.site/'
project('doceria-amorelli','Doceria Amorelli','sites','Gastronomia','Uma experiência digital tão convidativa quanto a vitrine.','Apresentar a doceria com personalidade e facilitar a descoberta da marca.','Uma presença digital dedicada à experiência da doceria, com acesso ao projeto publicado.',url=sitebase.format('doceria-amorelli-experiencia'),features=['Identidade visual','Apresentação do negócio','Experiência digital'],color='#d690a8')
project('jjang-natal','Jjang! Korean Market','sites','Varejo','Uma nova vitrine para o universo coreano em Natal.','Dar ao público um lugar para conhecer a loja antes de iniciar uma conversa.','Uma página de apresentação que aproxima a identidade da loja de seus futuros clientes.',url=sitebase.format('jjang-natal'),features=['Apresentação da loja','Identidade de marca','Jornada de contato'],color='#b9e270')
project('loma-original','Loma · Original','sites','Contabilidade','Clareza e presença para uma marca de assessoria contábil.','Traduzir os serviços contábeis em uma apresentação acessível para empresários.','Uma primeira direção visual para a presença digital da Loma, preservada para comparação.',url=sitebase.format('loma-versao-original'),features=['Site institucional','Apresentação de serviços','Versão original'],color='#b89763')
project('loma-assessoria','Loma · Assessoria','sites','Contabilidade','Outra perspectiva para a mesma marca.','Explorar uma nova maneira de apresentar os serviços da assessoria.','Uma segunda proposta de experiência e direção visual para a Loma.',url=sitebase.format('loma-assessoria'),features=['Site institucional','Direção visual alternativa','Jornada comercial'],color='#688bb3')
project('nails2you','Nails2You Moema','sites','Beleza','Presença digital com a personalidade de um espaço de beleza.','Apresentar o espaço e criar um caminho claro até o contato.','Uma experiência de marca para conectar o público ao universo da Nails2You.',url=sitebase.format('nails2you-moema'),features=['Site de apresentação','Experiência mobile','Identidade visual'],color='#dc91b0')
project('ela-bella','Ela Bella Esmalteria','sites','Beleza','O cuidado com a experiência começa antes da visita.','Levar a apresentação do negócio para além das redes sociais.','Um site dedicado à marca e à descoberta dos seus serviços.',url=sitebase.format('ela-bella-esmalteria'),features=['Presença digital','Apresentação da marca','Navegação responsiva'],color='#c4a7d4')
project('valentina-marques','Valentina Marques','sites','Beleza','Beleza em movimento, também no digital.','Mostrar a identidade do salão e valorizar a apresentação dos serviços.','Uma experiência visual com movimento e um caminho para conhecer o salão.',url=sitebase.format('valentina-marques-salao'),features=['Experiência visual','Apresentação do salão','Interações'],color='#c99a7b')
project('dream-home-finder','Dream Home Finder','sites','Imobiliário','Uma presença digital para o mercado imobiliário.','Criar um espaço digital dedicado à descoberta de imóveis.','Projeto de site imobiliário com demonstração disponível no link externo.',url='https://dream-home-finder-000.lovable.app',features=['Projeto web','Segmento imobiliário','Demonstração online'],color='#7dacaa')
project('perfumaria-deluxe','Perfumaria Deluxe','sites','Varejo','Uma vitrine digital para o universo da perfumaria.','Apresentar uma marca de perfumaria em um ambiente próprio.','Projeto de presença digital para explorar a apresentação de produtos e da marca.',url='https://perfumaria-deluxe.lovable.app',features=['Vitrine digital','Identidade visual','Projeto web'],color='#c4ae7d')
project('vic-franca-shop','Vic Franca Shop','sites','E-commerce · Shopify','Uma loja própria para levar a marca ao digital.','Apresentar os produtos da marca em uma estrutura de comércio eletrônico.','Loja desenvolvida na plataforma Shopify, com acesso à experiência de compra pelo projeto publicado.',url='https://vic-franca-shop.myshopify.com/',features=['Loja online','Plataforma Shopify','Presença de marca'],color='#d8b394')
project('agenda-de-unha','Agenda de Unha','sistemas','SaaS · Beleza','Você cuida do talento. O sistema cuida da organização.','Mensagens acumuladas, agendamentos dispersos e tempo gasto com tarefas repetitivas.','Agenda, catálogo, clientes, financeiro e atendimento com IA no WhatsApp conectados em um sistema.',image='agenda-agenda.webp',url='https://agendadeunha.com.br/',features=['Agendamento online','Agente de IA no WhatsApp','Financeiro e relatórios','Catálogo de serviços'],gallery=['agenda-agente.webp','agenda-financeiro.webp','agenda-agendar.webp','agenda-relatorios.webp'],color='#bb89fa',label='Produto próprio')
project('conversa-interativa','Agenda de Unha · Conversa','sistemas','Funil interativo','Uma apresentação que acontece em forma de conversa.','Explicar um produto sem obrigar o visitante a percorrer uma apresentação extensa.','Um fluxo interativo com respostas guiadas, vídeo explicativo e encaminhamento ao checkout.',url=sitebase.format('agenda-de-unha-conversa'),features=['Conversa guiada','Vídeo de apresentação','Encaminhamento ao checkout','Medição com pixel'],color='#b895db')
project('central-afiliados','CYPK · Central de Afiliados','sistemas','CRM · Vendas','Da indicação ao acompanhamento comercial.','Organizar indicações, leads e comissões em uma operação de vendas.','Um portal com links por vendedor, CRM e acompanhamento de comissões.',image='afil-painel.webp',url='https://sistemacypk.2.25.228.26.sslip.io/entrar',features=['CRM de leads','Links de indicação','Comissões','Painel do vendedor'],gallery=['afil-crm.webp','afil-comissao-vendedor.webp'],label='Acesso mediante login')
project('sistema-cafeteria','Sistema para Cafeteria','sistemas','Gestão · Alimentação','Do pedido ao fechamento do caixa.','Conectar o salão, a cozinha e o controle financeiro da cafeteria.','Uma operação integrada com comandas, mesas, cozinha, estoque e relatórios.',image='cafe-dashboard.webp',features=['Comandas e mesas','Painel da cozinha','Estoque','Caixa e relatórios'],gallery=['cafe-cozinha.webp','cafe-mesas.webp','cafe-estoque.webp','cafe-relatorios.webp'],color='#cf9c6c')
project('atendente-ia','Atendente de IA','sistemas','Automação · WhatsApp','Atendimento com contexto e espaço para a sua equipe.','Responder perguntas recorrentes sem perder o controle sobre as conversas.','Um agente conectado à base de conhecimento do negócio, com painel e transferência para atendimento humano.',image='wa-painel.webp',features=['Base de conhecimento','Painel de conversas','Transferência para a equipe'],gallery=['wa-conversa.webp'],color='#56c5b5')
project('veliora','Veliora','sistemas','SaaS · Agendamento','Organização para negócios com hora marcada.','Coordenar serviços, profissionais e horários em um só ambiente.','Uma plataforma de agenda e financeiro com página pública de agendamento.',image='vel-agenda.webp',features=['Agenda de serviços','Múltiplos profissionais','Página de agendamento','Financeiro'],gallery=['vel-agendar.webp','vel-financeiro.webp'],color='#b395db',label='Produto próprio')
project('central-campanha','Central de Campanha','sistemas','Gestão · Campanhas','Uma visão organizada de cada origem de acesso.','Conectar páginas de campanha, QR Codes e acompanhamento de interações.','Uma central com editor de página, QR Codes por origem e painel de acompanhamento.',image='camp-analytics.webp',features=['QR Codes por origem','Editor de página','Painel de métricas'],gallery=['camp-qrcodes.webp','camp-landing-editor.webp'],color='#76afcf')
project('portal-imobiliario','Portal Imobiliário','sistemas','Site + Gestão','Uma vitrine de imóveis com gestão própria.','Atualizar imóveis sem depender de uma alteração no código a cada anúncio.','Site com busca, páginas dos imóveis e painel para administrar o catálogo.',image='imov-home.webp',features=['Busca com filtros','Galeria de imóveis','Painel administrativo','Contato contextual'],gallery=['imov-listagem.webp','imov-detalhe.webp','imov-admin.webp'],color='#7dacaa')
for slug,name,sector,headline,desc,color in [('campanha-beleza','Beleza · Agendamentos','Serviços locais','Seu próximo horário começa com uma conversa.','Conceito de campanha com anúncio, página de apresentação e contato para agendamento.','#d792bc'),('campanha-varejo','Varejo · Descoberta','Comércio','Sua próxima descoberta está aqui.','Conceito de campanha para apresentar uma coleção e direcionar o público à vitrine digital.','#6ed9c1'),('campanha-b2b','B2B · Captação','Serviços empresariais','Seu negócio cresceu. Sua estrutura acompanhou?','Conceito de campanha para conectar uma oferta de serviço a uma página de captação.','#8a9cff')]:
 project(slug,name,'trafego',sector,headline,'Conectar mensagem, público e destino em uma campanha coerente.',desc,features=['Estratégia de mensagem','Conceito de criativo','Jornada até o contato'],color=color,label='Campanha ilustrativa')

categories={'sites':'Sites & landing pages','sistemas':'Sistemas, SaaS & CRM','trafego':'Tráfego pago'}
services=[('sites','Sites que apresentam o seu valor.','Sites & landing pages','Uma presença digital à altura do seu negócio.','Sua empresa precisa de um lugar próprio para apresentar o que faz e facilitar o próximo passo do cliente.',['Sites institucionais','Landing pages para campanhas','Vitrines e e-commerce','Experiência no celular e computador']),('sistemas','Uma operação mais organizada.','Sistemas, SaaS & CRM','Seu processo é único. A solução também pode ser.','Desenvolvemos ferramentas para reunir informações, simplificar rotinas e acompanhar o que importa.',['Sistemas sob medida','Plataformas SaaS','CRM e ferramentas internas','Painéis e relatórios']),('automacoes','Menos repetição. Mais possibilidades.','Automações & IA','O atendimento pode continuar quando você está ocupado.','Conectamos ferramentas e criamos automações para reduzir tarefas manuais e apoiar sua equipe.',['Agentes de IA no WhatsApp','Agendamentos e confirmações','Integrações entre sistemas','Fluxos de acompanhamento']),('trafego','Sua oferta na direção certa.','Gestão de tráfego pago','Mensagem, campanha e destino trabalhando juntos.','Planejamento, configuração e acompanhamento de campanhas com foco no objetivo do seu negócio.',['Campanhas em Meta Ads e Google Ads','Estratégia de público e mensagem','Páginas de destino','Configuração de métricas e acompanhamento'])]

def link(url,text,cls='button',external=False):return f'<a class="{cls}" href="{h(url)}"'+(' target="_blank" rel="noopener noreferrer"' if external else '')+f'>{text}</a>'
def eyebrow(t):return f'<p class="eyebrow">{t}</p>'
def cover(p):
 if p['image']:return f'<div class="project-visual screen"><div class="browser-bar"><i></i><i></i><i></i><span>{h(p["name"])}</span></div><img src="/assets/{p["image"]}" alt="Tela do projeto {h(p["name"])}" loading="lazy" width="1440" height="900"></div>'
 # These are explicitly typographic project covers, not invented screenshots.
 return f'<div class="project-visual brand-cover" style="--project-color:{p["color"]}"><span class="cover-kind">{h(p["sector"])}</span><strong>{h(p["desc"] if p["category"]=="trafego" else p["name"])}</strong><span class="cover-bottom">{("CONCEITO ILUSTRATIVO" if p["category"]=="trafego" else "PROJETO WEB · CYPK")}</span><span class="cover-orbit" aria-hidden="true"></span></div>'
def card(p):return f'<article class="project-card reveal" data-category="{p["category"]}" data-search="{h((p["name"]+" "+p["sector"]).lower())}"><a href="/portfolio/{p["slug"]}/" aria-label="Conhecer {h(p["name"])}">{cover(p)}<div class="project-meta"><span>{h(p["sector"])}</span><span>↗</span></div><h3>{h(p["name"])}</h3><p>{h(p["desc"])}</p></a></article>'
def cta():return '<section class="cta wrap reveal">'+eyebrow('SEU PRÓXIMO PROJETO')+'<h2>O que podemos<br><span class="gradient">construir juntos?</span></h2><p>Conte onde sua empresa está e aonde você quer chegar.</p>'+link('/contato/','Vamos conversar')+'</section>'
def layout(title,body,path='/',active='',desc='Sites, sistemas, automações com IA e gestão de tráfego. Conheça os projetos da CYPK Soluções Digitais.'):
 nav=''.join(f'<a href="{url}"'+(' aria-current="page"' if active==label else '')+f'>{label}</a>' for label,url in [('Início','/'),('Soluções','/solucoes/'),('Portfólio','/portfolio/'),('Sobre','/sobre/')])
 return f'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{h(title)} | CYPK Soluções Digitais</title><meta name="description" content="{h(desc)}"><meta name="theme-color" content="#080b12"><link rel="canonical" href="https://cypkdigital.tech{path}"><link rel="icon" href="/favicon.png"><meta property="og:title" content="{h(title)} | CYPK"><meta property="og:description" content="{h(desc)}"><meta property="og:image" content="https://cypkdigital.tech/og.png"><meta property="og:url" content="https://cypkdigital.tech{path}"><meta property="og:type" content="website"><link rel="stylesheet" href="/styles.css"><script src="/app.js" defer></script></head><body><a class="skip" href="#conteudo">Pular para o conteúdo</a><div class="ambient" aria-hidden="true"></div><header class="header"><div class="nav wrap"><a class="brand" href="/" aria-label="CYPK, início"><img src="/assets/cypk-logo.png" width="150" height="55" alt="CYPK Soluções Digitais"></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation" aria-label="Abrir menu"><span></span><span></span></button><nav id="navigation" aria-label="Principal">{nav}{link('/contato/','Fale sobre seu projeto','button small')}</nav></div></header><main id="conteudo">{body}</main><footer class="footer wrap"><div><a class="brand" href="/"><img src="/assets/cypk-logo.png" alt="CYPK Soluções Digitais" width="150" height="55" loading="lazy"></a><p>Tecnologia à altura<br>do seu negócio.</p></div><div><strong>Explore</strong><a href="/solucoes/">Soluções</a><a href="/portfolio/">Portfólio</a><a href="/sobre/">Sobre a CYPK</a></div><div><strong>Vamos conversar</strong><a href="/contato/">Começar um projeto</a><a href="mailto:cypk@gmail.com">cypk@gmail.com</a><a href="https://instagram.com/cypkdigital" target="_blank" rel="noopener noreferrer">Instagram · @cypkdigital</a></div><div class="footer-bottom"><span>© {__import__('datetime').date.today().year} CYPK · Soluções Digitais</span><span>Design com intenção. Tecnologia com propósito.</span><button class="motion-toggle" aria-pressed="false">Pausar animações</button></div></footer><dialog id="image-dialog"><button class="dialog-close" aria-label="Fechar imagem">Fechar ✕</button><img alt="Prévia ampliada do projeto"><p></p></dialog></body></html>'''
pages=[]
def write(path,title,body,active='',desc=None):
 folder=OUT/path.strip('/');folder.mkdir(parents=True,exist_ok=True);(folder/'index.html').write_text(layout(title,body,path,active,**({'desc':desc} if desc else {})));pages.append(path)
def servicecards():return '<div class="service-grid">'+''.join(f'<a class="service-card reveal" href="/solucoes/{s[0]}/"><span class="service-number">0{i+1} /</span><h3>{s[2]}</h3><p>{s[1]}</p><span class="text-link">Explorar solução ↗</span></a>' for i,s in enumerate(services))+'</div>'
hero='''<section class="cinema-hero" aria-label="Apresentação CYPK"><div class="cinema-stage"><video class="cinema-video" muted playsinline preload="none" poster="/assets/cypk-hero-poster.webp" data-src="https://cdn.21st.dev/assets/mirror/21/21a77eac28eacbb7e142016eefeaa0b4a766619e51113629a3bc6df6af066c0f.mp4" aria-hidden="true"></video><div class="cinema-shade" aria-hidden="true"></div><div class="cinema-top"><span>CYPK / SOLUÇÕES DIGITAIS</span><a href="#apos-hero">Pular introdução ↘</a></div><div class="cinema-opening"><p class="eyebrow">ESTRATÉGIA. DESIGN. TECNOLOGIA.</p><h1>Abra as portas para<br><span class="gradient">o próximo nível.</span></h1><p>Sites, sistemas e inteligência artificial<br>à altura do seu negócio.</p></div><div class="cinema-payoff" aria-hidden="true"><img src="/assets/cypk-logo.png" alt="CYPK Soluções Digitais" width="230" height="84"><p>Seu potencial.<br><span class="gradient">Uma nova dimensão digital.</span></p></div><div class="cinema-bottom"><div class="cinema-hint"><span>ROLE PARA EXPLORAR</span><span aria-hidden="true">↓</span></div><div class="actions">'''+link('/portfolio/','Explore nossos projetos')+link('/contato/','Começar um projeto','button ghost')+'''</div><span class="cinema-signature">DESIGN COM INTENÇÃO.<br>TECNOLOGIA COM PROPÓSITO.</span></div><div class="cinema-progress" aria-hidden="true"><span></span></div></div></section><div id="apos-hero" tabindex="-1"></div>'''
intro='<section class="statement wrap reveal"><span>FEITO PARA O SEU NEGÓCIO</span><h2>Uma boa solução digital<br>começa com <em>um problema real.</em></h2><p>Entendemos sua rotina para criar o que faz sentido: uma presença mais forte, uma operação mais simples ou um novo caminho até seus clientes.</p></section>'
home=hero+'<div class="expertise-strip"><div class="wrap">SITES & LANDING PAGES <i>✳</i> SISTEMAS & CRM <i>✳</i> AUTOMAÇÕES & IA <i>✳</i> TRÁFEGO PAGO</div></div>'+intro+'<section class="section wrap"><div class="section-heading">'+eyebrow('01 / NOSSAS SOLUÇÕES')+'<h2>O próximo passo<br>tem muitas formas.</h2></div>'+servicecards()+'</section><section class="section wrap"><div class="section-heading heading-row"><div>'+eyebrow('02 / TRABALHOS SELECIONADOS')+'<h2>Ideias que já<br>saíram do papel.</h2></div>'+link('/portfolio/','Ver portfólio completo','button ghost')+'</div><div class="project-grid">'+''.join(card(next(p for p in projects if p['slug']==slug)) for slug in ['agenda-de-unha','doceria-amorelli','sistema-cafeteria','loma-assessoria'])+'</div></section><section class="founder-teaser wrap reveal"><img src="/assets/elizeu-sena.jpeg" alt="Elizeu Sena, sócio-fundador da CYPK" width="1086" height="1448" loading="lazy"><div>'+eyebrow('03 / QUEM ESTÁ POR TRÁS')+'<h2>Tecnologia feita<br>por quem entende<br><span class="gradient">a sua ideia.</span></h2><p>Elizeu Sena, sócio-fundador da CYPK e desenvolvedor do Agenda de Unha. Um contato próximo entre quem precisa da solução e quem a constrói.</p>'+link('/sobre/','Conheça a CYPK','button ghost')+'</div></section>'+cta()
write('/','Tecnologia à altura do seu negócio',home,'Início')
write('/solucoes/','Soluções para o seu negócio','<section class="page-intro wrap">'+eyebrow('SOLUÇÕES CYPK')+'<h1>Da presença digital<br>à <span class="gradient">operação inteligente.</span></h1><p>Escolha o desafio. Nós ajudamos a construir o caminho.</p></section><section class="wrap section compact">'+servicecards()+'</section><section class="wrap section"><div class="section-heading">'+eyebrow('COMO TRABALHAMOS')+'<h2>Clareza em cada etapa.</h2></div><div class="steps"><article><span>01</span><h3>Entender</h3><p>Conversamos sobre o negócio, o público e o problema que precisa ser resolvido.</p></article><article><span>02</span><h3>Desenhar</h3><p>Definimos escopo, experiência e prioridades antes de desenvolver.</p></article><article><span>03</span><h3>Construir</h3><p>Transformamos a proposta em uma solução que você pode acompanhar.</p></article><article><span>04</span><h3>Colocar em uso</h3><p>Validamos os fluxos e orientamos os próximos passos da operação.</p></article></div></section>'+cta(),'Soluções')
for s in services:
 related=[p for p in projects if p['category']==('sistemas' if s[0]=='automacoes' else s[0])][:3]
 body='<section class="page-intro wrap">'+eyebrow(s[2].upper())+f'<h1>{s[3]}</h1><p>{s[4]}</p>'+link('/contato/?servico='+s[0],'Conversar sobre esta solução')+'</section><section class="section wrap split"><div><h2>O que podemos<br><span class="gradient">construir.</span></h2></div><div class="feature-list">'+''.join(f'<div><span>0{i+1}</span><h3>{v}</h3></div>' for i,v in enumerate(s[5]))+'</div></section><section class="section wrap"><div class="section-heading"><h2>'+('Conceitos de campanha' if s[0]=='trafego' else 'Explore possibilidades reais')+'</h2>'+('<p>Estudos ilustrativos de estratégia e criativo. Não representam campanhas contratadas nem resultados obtidos.</p>' if s[0]=='trafego' else '')+'</div><div class="project-grid three">'+''.join(card(p) for p in related)+'</div></section>'+cta()
 write('/solucoes/'+s[0]+'/',s[2],body,'Soluções')
filters='<div class="portfolio-controls"><div class="filters" role="group" aria-label="Categorias do portfólio">'+''.join(f'<button data-filter="{key}" aria-pressed="{str(key=="todos").lower()}">{val}</button>' for key,val in [('todos','Todos'),*categories.items()])+'</div><label class="search"><span class="sr-only">Buscar projetos</span><input type="search" placeholder="Buscar um projeto" id="project-search"></label></div>'
write('/portfolio/','Portfólio','<section class="page-intro wrap">'+eyebrow('PORTFÓLIO / CYPK')+'<h1>Mais que ideias.<br><span class="gradient">Projetos para explorar.</span></h1><p>Sites, produtos e sistemas. Diferentes desafios, o mesmo cuidado com a experiência.</p></section><section class="wrap section compact">'+filters+'<p class="result-count" aria-live="polite"></p><div class="project-grid" id="projects">'+''.join(card(p) for p in projects)+'</div><p id="no-results" hidden>Nenhum projeto encontrado. Tente outro nome ou categoria.</p><p class="portfolio-note">As campanhas de tráfego são estudos ilustrativos, sem resultados comerciais atribuídos. Os projetos web com capa tipográfica podem ser explorados pelo link da demonstração. As telas dos sistemas usam dados de demonstração.</p></section>'+cta(),'Portfólio')
for p in projects:
 gallery=([p['image']] if p['image'] else [])+list(p['gallery'])
 images='<div class="case-gallery">'+''.join(f'<button class="zoom-image" data-image="/assets/{im}" data-caption="{h(p["name"])} · tela de demonstração" aria-label="Ampliar tela de {h(p["name"])}"><img src="/assets/{im}" loading="lazy" alt="Tela de demonstração de {h(p["name"])}" width="1440" height="900"><span>Ampliar imagem +</span></button>' for im in gallery)+'</div>' if gallery else cover(p)
 body='<section class="case-intro wrap">'+link('/portfolio/','← Voltar ao portfólio','back-link')+eyebrow(categories[p['category']].upper())+f'<h1>{h(p["name"])}</h1><p>{h(p["desc"])}</p><div class="case-tags"><span>{h(p["sector"])}</span><span>{p["label"]}</span></div></section><section class="wrap">'+images+'</section><section class="section wrap case-story"><div>'+eyebrow('O DESAFIO')+f'<h2>{h(p["problem"])}</h2></div><div>'+eyebrow('A SOLUÇÃO')+f'<p class="large-copy">{h(p["solution"])}</p><ul class="checks">'+''.join(f'<li>{h(f)}</li>' for f in p['features'])+'</ul>'+ (link(p['url'],'Abrir projeto' if p['label']!='Acesso mediante login' else 'Abrir acesso ao sistema',external=True) if p['url'] else link('/contato/','Solicitar uma demonstração'))+('<p class="small-note">Estudo ilustrativo. Sem investimento, métricas ou resultados reais atribuídos a esta campanha.</p>' if p['category']=='trafego' else '')+'</div></section>'+cta()
 write('/portfolio/'+p['slug']+'/',p['name'],body,'Portfólio',p['desc'])
about='<section class="page-intro wrap">'+eyebrow('SOBRE A CYPK')+'<h1>Por trás da tecnologia,<br><span class="gradient">um olhar para o negócio.</span></h1><p>Criamos soluções digitais para aproximar ideias de quem precisa delas.</p></section><section class="bio wrap"><div class="portrait"><img src="/assets/elizeu-sena.jpeg" alt="Elizeu Sena, sócio-fundador da CYPK, em seu ambiente de trabalho" width="1086" height="1448"><span>ELIZEU SENA / CYPK</span></div><div>'+eyebrow('SÓCIO-FUNDADOR')+'<h2>Elizeu Sena</h2><p class="large-copy">Desenvolvedor e empreendedor, com foco em transformar necessidades do dia a dia em soluções digitais.</p><p>À frente da CYPK Soluções Digitais, Elizeu atua na criação de sites, sistemas e automações com inteligência artificial. Seu trabalho conecta a apresentação de uma empresa à organização dos processos que acontecem nos bastidores.</p><p>É o desenvolvedor do Agenda de Unha, uma ferramenta criada para ajudar manicures e nail designers a organizar agendamentos e automatizar o atendimento pelo WhatsApp.</p><p>Na CYPK, participa da definição da solução e do seu desenvolvimento, mantendo uma conversa próxima com cada negócio para entender o que realmente precisa ser construído.</p><div class="signature">Elizeu Sena<span>Sócio-fundador · CYPK Soluções Digitais</span></div>'+link('/contato/','Vamos falar sobre sua ideia','button ghost')+'</div></section><section class="section wrap"><div class="steps"><article><span>01</span><h3>Escuta antes do código</h3><p>A solução começa pelo entendimento do seu negócio.</p></article><article><span>02</span><h3>Clareza para decidir</h3><p>Objetivos, escopo e prioridades traduzidos em uma proposta compreensível.</p></article><article><span>03</span><h3>Tecnologia com utilidade</h3><p>Uma experiência que precisa funcionar para quem vai usá-la.</p></article></div></section>'+cta()
write('/sobre/','Sobre a CYPK e Elizeu Sena',about,'Sobre')
contact='<section class="page-intro wrap">'+eyebrow('VAMOS CONVERSAR')+'<h1>Sua próxima ideia<br><span class="gradient">começa aqui.</span></h1><p>Conte um pouco sobre seu negócio. Vamos entender o que faz sentido para você.</p></section><section class="contact-layout wrap section compact"><div><h2>Uma conversa.<br>Muitas possibilidades.</h2><p>Preencha um breve resumo para preparar sua mensagem. Você revisa tudo antes de abrir o WhatsApp.</p><div class="contact-info"><span>WHATSAPP</span><a href="https://wa.me/5583991053672" target="_blank" rel="noopener noreferrer">(83) 99105-3672</a><span>E-MAIL</span><a href="mailto:cypk@gmail.com">cypk@gmail.com</a><span>INSTAGRAM</span><a href="https://instagram.com/cypkdigital" target="_blank" rel="noopener noreferrer">@cypkdigital</a></div></div><form id="brief-form"><label>Como você se chama?<input name="nome" autocomplete="name" required maxlength="100" placeholder="Seu nome"></label><label>Qual é o seu negócio?<input name="empresa" autocomplete="organization" required maxlength="150" placeholder="Nome da empresa ou atividade"></label><label>Do que você precisa?<select name="servico" required><option value="">Selecione uma solução</option value="sites">Sites e landing pages</option><option value="sistemas">Sistemas, SaaS e CRM</option><option value="automacoes">Automações e IA</option><option value="trafego">Gestão de tráfego pago</option><option value="orientacao">Quero entender as possibilidades</option></select></label><label>O que você gostaria de melhorar?<textarea name="mensagem" required maxlength="2000" rows="4" placeholder="Conte o objetivo ou a dificuldade que quer resolver."></textarea></label><button class="button" type="submit">Preparar minha mensagem</button><p class="small-note">Este formulário não envia nem armazena seus dados. O contato só acontece quando você envia a mensagem no WhatsApp.</p><div id="message-preview" hidden><h3>Sua mensagem está pronta</h3><p id="message-text"></p><a class="button" id="whatsapp-link" target="_blank" rel="noopener noreferrer">Continuar no WhatsApp</a></div></form></section>'
write('/contato/','Vamos conversar',contact)
(OUT/'404.html').write_text(layout('Página não encontrada','<section class="page-intro wrap">'+eyebrow('404')+'<h1>Esse caminho<br>não existe.</h1><p>Vamos encontrar o que você procura.</p>'+link('/portfolio/','Explorar o portfólio')+'</section>'))
(OUT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>https://cypkdigital.tech'+p+'</loc></url>' for p in pages)+'</urlset>')
(OUT/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: https://cypkdigital.tech/sitemap.xml\n')
print(f'Generated {len(pages)} pages; {len(projects)} projects.')
